spring.datasource.url=jdbc:mysql://employeeadithyaserver.mysql.database.azure.com:3306/employee_management_system?useSSL=true
spring.datasource.username=jqyppqqsjl
spring.datasource.password=Adithya@6599

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto = update
